# Generated by Django 4.2.7 on 2024-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0002_mymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="Age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="Domain",
            field=models.CharField(default="Python", max_length=100),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="Language",
            field=models.CharField(default="Tamil", max_length=50),
        ),
    ]
