# Generated by Django 4.2.7 on 2024-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_mymodel_age_mymodel_domain_mymodel_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
            ],
        ),
    ]
