# Generated by Django 4.2.7 on 2024-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0004_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
